### ISSUE TITLE
Rename to simply ProjectMaker

### ISSUE THREAD

**Issue by pykong** [bit101/ProjectMaker#51]
According to `packagecontrol` recommendations a plugin should not contain `Sublime`, `SublimeText` or `ST` in its name. The context of Sublime Text is clear by the very fact that this package is a plugin.
I have renamed at least one plugin in the past and that renaming met a positive response by the users.

**Comment by bit101** [comment]
done

**Comment by pykong** [comment]
Awesome. Thanks!

**Comment by keith-notarize** [comment]
Thank you. Even though I don't currently use Sublime, it's nice to see the project carry on and see new life.
