### ISSUE TITLE
Consider integrating template engine

### ISSUE THREAD

**Issue by pykong** [bit101/ProjectMaker#56]
Maybe here is a low hanging fruit waiting for us to pick it:
There may be a way to grant **ProjectMaker** the super powers of a full-blown template engine.

This could make our code much simpler as we could just outsource the current file creation logic to an external library. It also would endow **ProjectMaker** with templating abilities going beyond mere string substitution. Namely iteration, conditionals and inheritance would enhance usability.

**Questions:**
1) Does it make sense at all? Do we want this?
2) Do we recreate the wheel? (like coding another [cookiecutter](https://github.com/audreyr/cookiecutter), at least another [GCnP](https://packagecontrol.io/packages/Glorified%20Copy%20%27n%27%20Paste))
3) Which templating engine to use? (likely [Jinja2](http://jinja.pocoo.org/docs/2.10/api/))
4) Should we stick with [boost libraries' format string]( http://www.boost.org/doc/libs/1_56_0/libs/regex/doc/html/boost_regex/format/boost_format_syntax.html) delimiters (`${...}`) or those native to the templating engine chosen? (Jinja2: ` {{...}}, {%...%}`)

**Comment by bit101** [comment]
I've actually been working on another project inspired by this. https://github.com/bit101/tinpig
It is kind of reinventing the wheel. Maybe I'm the only one who will use it. But it's been fun. Hope to release v1 by the weekend. Maybe sooner.

**Comment by bit101** [comment]
But don't let that stop you from taking this project other places.

**Comment by pykong** [comment]
@bit101 I am busy with other stuff right now. It will take me a couple of weeks to again attend to further development. Then I am going to make this Package 2.0.: #53

**Comment by pykong** [comment]
I am not moving forward with this idea. Closing.
